// var greeting = "hello";
// console.log(greeting);
// var greeting = "Hi";
// console.log(greeting);
// var greeting = "how are you?";
// console.log(greeting);
// let greeting = "hello";
// console.log(greeting);
// greeting = "hi";
// console.log(greeting);
const greeting = "hello";
console.log(greeting);
